# encoding: utf-8# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

if ENV['RAILS_ENV'] = 'development'
  User.delete_all
  Profile.delete_all
  BasketItem.delete_all
  Ticket.delete_all

  User.create email: 'super@example.com', password: 'password', profile_attributes: { name: 'Admin', phones: 'Phones...' }
  User::Moderator.create email: 'moderator@example.com', password: 'password', profile_attributes: { name: 'Moderator', phones: 'Phones...', agreement: '324542642' }
  User::Agency.create email: 'agency@example.com', password: 'password', profile_attributes: { name: 'Agency', phones: 'Phones...' }
end
