require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Hotels::BankAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # Hotels::BankAttribute. As you add validations to Hotels::BankAttribute, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Hotels::BankAttributesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hotels_bank_attributes as @hotels_bank_attributes" do
      bank_attribute = Hotels::BankAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hotels_bank_attributes).should eq([bank_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested bank_attribute as @bank_attribute" do
      bank_attribute = Hotels::BankAttribute.create! valid_attributes
      get :show, {:id => bank_attribute.to_param}, valid_session
      assigns(:bank_attribute).should eq(bank_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new bank_attribute as @bank_attribute" do
      get :new, {}, valid_session
      assigns(:bank_attribute).should be_a_new(Hotels::BankAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested bank_attribute as @bank_attribute" do
      bank_attribute = Hotels::BankAttribute.create! valid_attributes
      get :edit, {:id => bank_attribute.to_param}, valid_session
      assigns(:bank_attribute).should eq(bank_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hotels::BankAttribute" do
        expect {
          post :create, {:bank_attribute => valid_attributes}, valid_session
        }.to change(Hotels::BankAttribute, :count).by(1)
      end

      it "assigns a newly created bank_attribute as @bank_attribute" do
        post :create, {:bank_attribute => valid_attributes}, valid_session
        assigns(:bank_attribute).should be_a(Hotels::BankAttribute)
        assigns(:bank_attribute).should be_persisted
      end

      it "redirects to the created bank_attribute" do
        post :create, {:bank_attribute => valid_attributes}, valid_session
        response.should redirect_to(Hotels::BankAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bank_attribute as @bank_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hotels::BankAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:bank_attribute => {}}, valid_session
        assigns(:bank_attribute).should be_a_new(Hotels::BankAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hotels::BankAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:bank_attribute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bank_attribute" do
        bank_attribute = Hotels::BankAttribute.create! valid_attributes
        # Assuming there are no other hotels_bank_attributes in the database, this
        # specifies that the Hotels::BankAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hotels::BankAttribute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bank_attribute.to_param, :bank_attribute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bank_attribute as @bank_attribute" do
        bank_attribute = Hotels::BankAttribute.create! valid_attributes
        put :update, {:id => bank_attribute.to_param, :bank_attribute => valid_attributes}, valid_session
        assigns(:bank_attribute).should eq(bank_attribute)
      end

      it "redirects to the bank_attribute" do
        bank_attribute = Hotels::BankAttribute.create! valid_attributes
        put :update, {:id => bank_attribute.to_param, :bank_attribute => valid_attributes}, valid_session
        response.should redirect_to(bank_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the bank_attribute as @bank_attribute" do
        bank_attribute = Hotels::BankAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hotels::BankAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => bank_attribute.to_param, :bank_attribute => {}}, valid_session
        assigns(:bank_attribute).should eq(bank_attribute)
      end

      it "re-renders the 'edit' template" do
        bank_attribute = Hotels::BankAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hotels::BankAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => bank_attribute.to_param, :bank_attribute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bank_attribute" do
      bank_attribute = Hotels::BankAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => bank_attribute.to_param}, valid_session
      }.to change(Hotels::BankAttribute, :count).by(-1)
    end

    it "redirects to the hotels_bank_attributes list" do
      bank_attribute = Hotels::BankAttribute.create! valid_attributes
      delete :destroy, {:id => bank_attribute.to_param}, valid_session
      response.should redirect_to(hotels_bank_attributes_url)
    end
  end

end
