require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe User::HoteliersController do

  # This should return the minimal set of attributes required to create a valid
  # User::Agency. As you add validations to User::Agency, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # User::AgenciesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all user_hoteliers as @user_hoteliers" do
      hotelier = User::Hotelier.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_hoteliers).should eq([hotelier])
    end
  end

  describe "GET show" do
    it "assigns the requested hotelier as @hotelier" do
      hotelier = User::Hotelier.create! valid_attributes
      get :show, {:id => hotelier.to_param}, valid_session
      assigns(:hotelier).should eq(hotelier)
    end
  end

  describe "GET new" do
    it "assigns a new hotelier as @hotelier" do
      get :new, {}, valid_session
      assigns(:hotelier).should be_a_new(User::Hotelier)
    end
  end

  describe "GET edit" do
    it "assigns the requested hotelier as @hotelier" do
      hotelier = User::Hotelier.create! valid_attributes
      get :edit, {:id => hotelier.to_param}, valid_session
      assigns(:hotelier).should eq(hotelier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new User::Hotelier" do
        expect {
          post :create, {:hotelier => valid_attributes}, valid_session
        }.to change(User::Hotelier, :count).by(1)
      end

      it "assigns a newly created hotelier as @hotelier" do
        post :create, {:hotelier => valid_attributes}, valid_session
        assigns(:hotelier).should be_a(User::Hotelier)
        assigns(:hotelier).should be_persisted
      end

      it "redirects to the created hotelier" do
        post :create, {:hotelier => valid_attributes}, valid_session
        response.should redirect_to(User::Hotelier.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hotelier as @hotelier" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::Hotelier.any_instance.stub(:save).and_return(false)
        post :create, {:hotelier => {}}, valid_session
        assigns(:hotelier).should be_a_new(User::Hotelier)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        User::Hotelier.any_instance.stub(:save).and_return(false)
        post :create, {:hotelier => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hotelier" do
        hotelier = User::Hotelier.create! valid_attributes
        # Assuming there are no other user_hoteliers in the database, this
        # specifies that the User::Hotelier created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        User::Hotelier.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hotelier.to_param, :hotelier => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hotelier as @hotelier" do
        hotelier = User::Hotelier.create! valid_attributes
        put :update, {:id => hotelier.to_param, :agency => valid_attributes}, valid_session
        assigns(:hotelier).should eq(agency)
      end

      it "redirects to the hotelier" do
        hotelier = User::Hotelier.create! valid_attributes
        put :update, {:id => hotelier.to_param, :hotelier => valid_attributes}, valid_session
        response.should redirect_to(hotelier)
      end
    end

    describe "with invalid params" do
      it "assigns the hotelier as @hotelier" do
        hotelier = User::Hotelier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::Hotelier.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotelier.to_param, :hotelier => {}}, valid_session
        assigns(:hotelier).should eq(hotelier)
      end

      it "re-renders the 'edit' template" do
        hotelier = User::Hotelier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        User::Hotelier.any_instance.stub(:save).and_return(false)
        put :update, {:id => hotelier.to_param, :hotelier => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hotelier" do
      hotelier = User::Hotelier.create! valid_attributes
      expect {
        delete :destroy, {:id => hotelier.to_param}, valid_session
      }.to change(User::Hotelier, :count).by(-1)
    end

    it "redirects to the user_hotelier list" do
      hotelier = User::Hotelier.create! valid_attributes
      delete :destroy, {:id => hotelier.to_param}, valid_session
      response.should redirect_to(user_hoteliers_url)
    end
  end

end
